-- ============================================================
-- SEED: directorio de contactos por oficina (AFIMEX)
-- Ejecutar DESPUES de supabase_schema.sql en el SQL Editor de Supabase
-- ============================================================
insert into contactos_oficina (oficina, email_to, email_cc, jefe, jefe_oficina) values
('CIUDAD VALLES EXT', 'alfaroantoniocarlos@gmail.com', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('AGUASCALIENTES EXTENDIDA', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('MONTERREY  EXT', 'cachecg2004@gmail.com', 'cachecg2004@gmail.com', 'FABIÁN REQUENES', ''),
('ALAMO VERACRUZ', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('ALLENDE NL', 'envioshopallende@gmail.com', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('CAMARGO', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('CHIHUAHUA EXTENDIDAS', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('CHINA NL', 'jenidlc22@gmail.com', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('CERRO AZUL', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('CRUZ SALDIERNA', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('CIUDAD MANTE', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('NARANJOS VERACRUZ', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('MATEHUALA EXT', 'logisticafatsa@gmail.com', 'logisticafatsa@gmail.com', 'FABIÁN REQUENES', ''),
('DURANGO', 'gromeroh28@gmail.com', 'gromeroh28@gmail.com', 'FABIÁN REQUENES', ''),
('ESTACION MANUEL', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('GUACHOCHI', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('HIDALGO TAMAULIPAS', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('JIMENEZ', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('JIMENEZ CUU', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('LLERA DE CANALES', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('MATEHUALA', 'joelblancoseres@gmail.com', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('PARRAS COAH', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('TUXPAN VERACRUZ', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('POZA RICA', 'paulagarciademunoz@gmail.com', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('RIO VERDE', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('SABINAS COAHUILA', 'mostrador.sabinascoahuila@afimex.mx', 'mostrador.sabinascoahuila@afimex.mx', 'FABIÁN REQUENES', ''),
('SABINAS HIDALGO', 'mostradorsabinashidalgo@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('SAN FERNANDO', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('SOTO LA MARINA', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('TAMPICO EXTENDIDA', 'juanprado230981@gmail.com', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('TAMAZUNCHALE', 'yoenviotmz@gmail.com, manillaeva@gmail.com', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('TAMPICO MANTE', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('TULA', 'del.altiplano@gmail.com', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('VALLE HERMOSO', 'mostradorvallehermoso@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('VILLAGRAN', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('TORREON EXT', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('ZACATECAS', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('ZACATECAS EXT', 'fabian.requenes@afimex.mx', 'fabian.requenes@afimex.mx', 'FABIÁN REQUENES', ''),
('CHIHUAHUA', 'audrey.carnero@afimex.mx', '', 'FRANCISCO MARTINEZ', 'IVÁN MARTÍNEZ'),
('CIUDAD JUAREZ', 'david.carcamo@afimex.mx', '', 'FRANCISCO MARTINEZ', 'BLANCA MORENO'),
('CUAUHTEMOC', 'francisco.martinez@afimex.mx', '', 'FRANCISCO MARTINEZ', 'JESÚS BUSTILLOS'),
('DELICIAS', 'alejandro.orta@afimex.mx', '', 'FRANCISCO MARTINEZ', 'ALEJANDRO ORTA'),
('PARRAL', 'mayra.lopez@afimex.mx', '', 'FRANCISCO MARTINEZ', 'MAYRA LOPEZ'),
('TORREON', 'rafael.valdez@afimex.mx', '', 'FRANCISCO MARTINEZ', 'RAFAEL VALDEZ'),
('CIUDAD VALLES', 'mostradorcua@afimex.mx', '', 'JOSE SOLIS', 'GUILLERMO AVILA'),
('CIUDAD VICTORIA', 'nancy.marquez@afimex.mx', '', 'JOSE SOLIS', 'NANCY MÁRQUEZ'),
('LEON', 'pedro.celedonio@afimex.mx', '', 'JOSE SOLIS', 'PEDRO CELEDONIO'),
('SAN LUIS POTOSI', 'josue.moreno@afimex.mx', '', 'JOSE SOLIS', 'JOSUE MORENO'),
('TAMPICO CENTRAL', 'mostrador.tmpcentro@afimex.mx', '', 'JOSE SOLIS', ''),
('TAMPICO DIVISORIA', 'erick.rivera@afimex.mx', '', 'JOSE SOLIS', 'ERIK MELCHOR'),
('LINARES', 'laura.garcia@afimex.mx', '', 'KARINA MORENO', 'LAURA GARCIA'),
('MATAMOROS', 'gael.izaguirre@afimex.mx', '', 'KARINA MORENO', 'GAEL IZAGUIRRE'),
('MONCLOVA', 'oscar.montemayor@afimex.mx', '', 'KARINA MORENO', 'OSCAR MONTEMAYOR'),
('MONTERREY', 'adrian.gutierrez@afimex.mx', '', 'KARINA MORENO', 'ADRIÁN GUTIÉRREZ'),
('NUEVO LAREDO', 'abisag.tabita@afimex.mx', '', 'KARINA MORENO', 'ABISAG BANDA'),
('PIEDRAS NEGRAS', 'elsa.flores@afimex.mx', '', 'KARINA MORENO', 'ELSA FLORES'),
('REYNOSA', 'felix.martinez@afimex.mx', '', 'KARINA MORENO', 'ISRAEL MARTINEZ'),
('SALTILLO', 'juan.isais@afimex.mx', '', 'KARINA MORENO', 'KARINA MORENO')
on conflict (oficina) do update set
  email_to = excluded.email_to,
  email_cc = excluded.email_cc,
  jefe = excluded.jefe,
  jefe_oficina = excluded.jefe_oficina;
